spring:
   application:
      name: spirng-boot-rabbitmq-sender
   rabbitmq:
      host: rabbitmq.dev.com
      port: 5672
      username: guest
      password: guest
      listener:
         simple:
            acknowledge-mode: manual
server:
   port: 7081
mq:
   emp:
      exchange: eebo.iam.change_emp
      routingKey: eebo.iam.addOrUpdate_emp_key
