spring:
   application:
      name: spirng-boot-rabbitmq-sender
   rabbitmq:
      host: 120.77.214.1
      port: 5672
      username: admin
      password: admin
      publisher-confirms: true
      virtual-host: /
server:
   port: 7081
test:
   mq:
      exchange: testExchange
      routingKey: testKey
